[package]
name = "cloud-atlas"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
tokio = { version = "1.21", features = ["full"] }
uuid = { version = "1.2", features = ["v4"] }
aws-config = "0.49"
aws-sdk-config = "0.19"
aws-sdk-ec2 = "0.19"
aws-types = "0.49"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.0", features = ["derive", "unicode"] }
petgraph = "0.6"
