[package]
name = "atlas-lib"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/k-cross/cloud-atlas"
documentation = "https://github.com/k-cross/cloud-atlas"
keywords = ["AWS", "cloud", "graph", "infrastructure"]
license = "MPL2"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.56"
aws-sdk-config = "0.30"
aws-sdk-ec2 = "0.30"
aws-sdk-ecs = "0.30"
aws-sdk-eventbridge = "0.30"
aws-sdk-lambda = "0.30"
aws-types = "0.56"
futures = "0.3"
petgraph = "0.6"
tokio = { version = "1.21", features = ["full"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.2", features = ["v4"] }
